version: "3.7"

services:
  mongodb:
    # choose the proper mongodb version for the aplication instead of latest
    image: mongo:latest
    # environment:
    #   MONGO_INIDB_ROOT_USERNAME: mongoadmin
    #   MONGO_INIDB_ROOT_PASWWORD: secret
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb:
